### ISSUE TITLE
Add to the official community repo

### ISSUE THREAD

**Issue by kingthorin** [irgoncalves/aws-signing-for-owasp-zap#1]
@irgoncalves you should add this to the official community repo.

https://github.com/zaproxy/community-scripts

**Comment by irgoncalves** [comment]
Hi @kingthorin , thanks! I will work on that.

**Comment by kingthorin** [comment]
Mind if I do it?

**Comment by irgoncalves** [comment]
Hello @kingthorin , just did the pull request to add it to the Community Scripts. Let me know if everything looks good.

**Comment by irgoncalves** [comment]
Added to the official community repo.
